name: Horizons
description: Horizons template for Jekyll
paginate: 10
baseurl: "/dpjedi-website/" # the subpath of your site, e.g. /blog
url: "https://qualitativedatarepository.github.io/" # the base hostname & protocol for your site
